# DNS resolver
try_system_resolver = true
custom_resolvers = [
    "8.8.8.8:53",
]

# The DNS record to check
record = "test.ds.jamesits.eu.org"
# Record type: A, AAAA and TXT is supported
record_type = "TXT"

# A "normal" value
expected_value = "cHnkuqTmmJM="

# A "execute immediately" value
trigger_value = "5pyJ5YaF6ay877yM57uI5q2i5Lqk5piT77yB"

# Hooks
execute_scripts = [
    # Files or folders here
    # Non-executable files will be ignored
    "hooks"
]

delete_files = [
    # Files or folders here
]

# Config
# seconds between every check
check_interval = 60

# quit main program after one successful trigger
exit_after_trigger = true

trigger_on_uncertain = false
max_uncertain_tolerance = 3
